// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZamETF.Data;

#nullable disable

namespace ZamETF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZamETF.Models.AdminZahtjev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obradjen")
                        .HasColumnType("bit");

                    b.Property<int>("VrstaZahtjeva")
                        .HasColumnType("int");

                    b.Property<int>("ZahtjevId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("ZahtjevId");

                    b.ToTable("AdminZahtjevi");
                });

            modelBuilder.Entity("ZamETF.Models.Bodovanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bodovi")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Bodovanja");
                });

            modelBuilder.Entity("ZamETF.Models.Ispit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokZaPrijavu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("ZamETF.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ZamETF.Models.Ocjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Vrijednost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("ZamETF.Models.PredajaZadace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bodovi")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPredaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fajl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ZadacaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ZadacaId");

                    b.ToTable("PredajeZadace");
                });

            modelBuilder.Entity("ZamETF.Models.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("SifraPredmeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Predmeti");
                });

            modelBuilder.Entity("ZamETF.Models.PrijavaIspit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<int>("IspitId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IspitId");

                    b.HasIndex("StudentId");

                    b.ToTable("PrijaveIspita");
                });

            modelBuilder.Entity("ZamETF.Models.Prisustvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<bool>("Prisutan")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prisustva");
                });

            modelBuilder.Entity("ZamETF.Models.UpisNaPredmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<int>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("UpisaNaPredmet");
                });

            modelBuilder.Entity("ZamETF.Models.Zadaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazivID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rok")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.ToTable("Zadace");
                });

            modelBuilder.Entity("ZamETF.Models.ZahtjevZaDokument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentskaSluzbaId")
                        .HasColumnType("int");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentskaSluzbaId");

                    b.ToTable("ZahtjeviDokumenata");
                });

            modelBuilder.Entity("ZamETF.Models.Administrator", b =>
                {
                    b.HasBaseType("ZamETF.Models.Korisnik");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("ZamETF.Models.Profesor", b =>
                {
                    b.HasBaseType("ZamETF.Models.Korisnik");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("ZamETF.Models.Student", b =>
                {
                    b.HasBaseType("ZamETF.Models.Korisnik");

                    b.Property<int>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<string>("Indeks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredmetId")
                        .HasColumnType("int");

                    b.HasIndex("PredmetId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ZamETF.Models.StudentskaSluzba", b =>
                {
                    b.HasBaseType("ZamETF.Models.Korisnik");

                    b.HasDiscriminator().HasValue("StudentskaSluzba");
                });

            modelBuilder.Entity("ZamETF.Models.AdminZahtjev", b =>
                {
                    b.HasOne("ZamETF.Models.Administrator", "Administrator")
                        .WithMany("Zahtjevi")
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.ZahtjevZaDokument", "Zahtjev")
                        .WithMany()
                        .HasForeignKey("ZahtjevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Zahtjev");
                });

            modelBuilder.Entity("ZamETF.Models.Bodovanje", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany("Bodovanja")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.Ispit", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("ZamETF.Models.Ocjena", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany("Ocjene")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.PredajaZadace", b =>
                {
                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany("PredajeZadace")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Zadaca", "Zadaca")
                        .WithMany("Predaje")
                        .HasForeignKey("ZadacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Zadaca");
                });

            modelBuilder.Entity("ZamETF.Models.Predmet", b =>
                {
                    b.HasOne("ZamETF.Models.Profesor", "Profesor")
                        .WithMany("Predmeti")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ZamETF.Models.PrijavaIspit", b =>
                {
                    b.HasOne("ZamETF.Models.Ispit", "Ispit")
                        .WithMany("Prijave")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany("PrijaveIspita")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.Prisustvo", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany("Prisustva")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.UpisNaPredmet", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.Zadaca", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", "Predmet")
                        .WithMany("Zadace")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("ZamETF.Models.ZahtjevZaDokument", b =>
                {
                    b.HasOne("ZamETF.Models.Student", "Student")
                        .WithMany("Zahtjevi")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZamETF.Models.StudentskaSluzba", null)
                        .WithMany("Zahtjevi")
                        .HasForeignKey("StudentskaSluzbaId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZamETF.Models.Student", b =>
                {
                    b.HasOne("ZamETF.Models.Predmet", null)
                        .WithMany("Studenti")
                        .HasForeignKey("PredmetId");
                });

            modelBuilder.Entity("ZamETF.Models.Ispit", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("ZamETF.Models.Predmet", b =>
                {
                    b.Navigation("Bodovanja");

                    b.Navigation("Ocjene");

                    b.Navigation("Prisustva");

                    b.Navigation("Studenti");

                    b.Navigation("Zadace");
                });

            modelBuilder.Entity("ZamETF.Models.Zadaca", b =>
                {
                    b.Navigation("Predaje");
                });

            modelBuilder.Entity("ZamETF.Models.Administrator", b =>
                {
                    b.Navigation("Zahtjevi");
                });

            modelBuilder.Entity("ZamETF.Models.Profesor", b =>
                {
                    b.Navigation("Predmeti");
                });

            modelBuilder.Entity("ZamETF.Models.Student", b =>
                {
                    b.Navigation("PredajeZadace");

                    b.Navigation("PrijaveIspita");

                    b.Navigation("Zahtjevi");
                });

            modelBuilder.Entity("ZamETF.Models.StudentskaSluzba", b =>
                {
                    b.Navigation("Zahtjevi");
                });
#pragma warning restore 612, 618
        }
    }
}
